Repository harshmittal1750/hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#2 Create LICENSE
  LICENSE
Labels: hacktoberfest2022

#3 Adding solution of leetcode question
  JAVA/roman-to-integer.java
Labels: hacktoberfest2022, hacktoberfest-2022, Programmer

#4 Added Anagram prime reverse and subset programs
  JAVA/Anagaram_with_substring.java
  JAVA/Reversing_Sentence_Without reversing_word.java
  JAVA/prime_add.java
  JAVA/subset_array.java
Labels: hacktoberfest2022, hacktoberfest-2022, Programmer

#6 Making Repo and New Branch
  JAVA/Roman to Integer/roman-to-integer.java
Labels: enhancement, hacktoberfest2022, hacktoberfest-2022

#5 Create Kadane Algorithm in java
  JAVA/Kadane Algorithm in java
  JAVA/Merge sort code in java
Labels: hacktoberfest2022, hacktoberfest-2022, Programmer

#8 added promise example
  JS/promiseExample.js
Labels: hacktoberfest2022, hacktoberfest-2022, good contributer, super contributer, Programmer, hacktoberfest-accepted

#10 Create oddOrEven.py
  Python/oddOrEven.py
Labels: hacktoberfest2022, hacktoberfest-2022, first contibuter, Programmer, hacktoberfest-accepted

#9 hacktoberfest-2022
  Algorithms/BubbleSort.java
  Algorithms/BucketSort.java
  Algorithms/CycleSort.java
  Algorithms/HeapSort.java
  Algorithms/InsertionSort.java
  Algorithms/MergeSort.java
  Algorithms/QuickSort.java
  Algorithms/RadixSort.java
  Algorithms/SelectionSort.java
  Algorithms/ShellSort.java
  Algorithms/TreeSort.java
Labels: hacktoberfest2022, hacktoberfest-2022, first contibuter, Programmer, hacktoberfest-accepted

#12 [Python] Radix Sort
  Python/radixSort.py
Labels: hacktoberfest2022, hacktoberfest-2022, first contibuter, Programmer, hacktoberfest-accepted

#11 [Python] Counting Sort for String value
  Python/countingSortString.py
Labels: hacktoberfest2022, hacktoberfest-2022, Programmer, hacktoberfest-accepted

#14 [Python] Quick Sort
  Python/quickSort.py
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#15 add palindromeexample.java file
  JAVA/PalindromeExample.java
Labels: hacktoberfest2022, hacktoberfest-2022, Programmer, hacktoberfest-accepted

#16 Added Knapsack Problem
  JAVA/Knapsack_Problem.java
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#17 Create insertionSort.java
  JAVA/insertionSort.java
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#18 Added bubble sort algorithm
  JAVA/bubbleSort.java
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#20 Added BinarySearch.py
  Python/BinarySearch.py
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#19 Find Prime numbers upto N
  JAVA/SieveOfEratosthenes.class
  JAVA/SieveOfEratosthenes.java
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#21 factorial and palindrome functions added
  Python/Factorial.py
  Python/Palindrome.py
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#22 Added SelectionSort.java
  JAVA/SelectionSort.java
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#23 Binary Search using Recursion
  JAVA/binarySearch.java
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#24 2dArray
  JAVA/2dArray/FindElementInSortedArray.java
  JAVA/2dArray/RingRotate.java
  JAVA/2dArray/Rotateby90degree.java
  JAVA/2dArray/SaddlePoint.java
  JAVA/2dArray/StateOfWakanda2.java
Labels: hacktoberfest2022, hacktoberfest-2022, good contributer, Programmer, hacktoberfest-accepted

#25 Screen Pet with Python.py
  Screen Pet with Python.py
Labels: hacktoberfest2022, hacktoberfest-2022, Programmer, hacktoberfest-accepted

#26 add java design patterns - singleton pattern
  JAVA/designPatterns/ThreadSafeSingleton.java
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#27 2D Array Row-wise Sum
  C++/2dArrRowwiseSum.cpp
  C++/2dArrRowwiseSum.exe
Labels: hacktoberfest2022, hacktoberfest-2022, good contributer, Programmer, hacktoberfest-accepted

#28 Create edmonds_karp_algorithm.cpp
  edmonds_karp_algorithm.cpp
Labels: hacktoberfest2022, hacktoberfest-2022, Programmer, hacktoberfest-accepted

#29 BubbleSort.py
  Python/BubbleSort.py
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#30 Added Job Sequencing
  JAVA/jobSequencing.java
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#42 Create LinearSearch.cpp
  C++/LinearSearch.cpp
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#39 Added Factorial.java
  JAVA/Factorial.java
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#31 Make new android apps
  ANDROID_PROJECT/Angkot Apps/.idea/.gitignore
  ANDROID_PROJECT/Angkot Apps/.idea/compiler.xml
  ANDROID_PROJECT/Angkot Apps/.idea/gradle.xml
  ANDROID_PROJECT/Angkot Apps/.idea/misc.xml
  ANDROID_PROJECT/Angkot Apps/.idea/vcs.xml
  ANDROID_PROJECT/README.md
Labels: documentation, enhancement, hacktoberfest2022, hacktoberfest-2022, good contributer, Programmer, hacktoberfest-accepted

#32 Create all characters of string whose frequency is a power of K.py
  Python/all characters of string whose frequency is a power of K.py
Labels: hacktoberfest2022, hacktoberfest-2022, Programmer, hacktoberfest-accepted

#34 add RockPaperScissors.java
  JAVA/RockPaperScissors.java
Labels: hacktoberfest2022, hacktoberfest-2022, Programmer, hacktoberfest-accepted

#36 Feat(add Event indonesia drawing turtle)
  Python/drawIndonesianEvent.py
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#35 InterestingPattern
  C++/Pattern
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#37 Create BinarySearch.java
  Algorithms/BinarySearch.java
  JAVA/BinarySearch.java
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#40 Implement Count Sort
  C/CountSort.c
  Practice_PR.md
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#41 Create Radix-Sort.cpp
  C++/Radix-Sort.cpp
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#43 Added mergeSort in Python
  Python/mergeSort.py
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#45 Added sudoku_solver.py
  Python/sudoku_solver.py
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#46 Added Infix to Postfix in C++
  C++/INFIXPOST.cpp
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#47 Create interface.go
  Go/interface.go
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#49 Majority Element usinh HashMap
  JAVA/majelem.java
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#50 binary-tree-from-inorder-and-postorder-traversal
  C++/106.construct-binary-tree-from-inorder-and-postorder-traversal.cpp
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#51 Hacktobrfest2022 binarySearch.java
  JAVA/binarySearch.java
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#52 Multiple Inheritance Program in C++
  C++/multiple inheritance.cpp
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#53 add longestSubStr.java program
  JAVA/longestSubStr.java
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#54 Create heart.java
  JAVA/designPatterns/heart.java
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#55 Quick Sort Algorithm in Java added
  JAVA/QuickSort.java
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted

#57 Create radix_sort.java
  JAVA/radix_sort.java
Labels: hacktoberfest2022, hacktoberfest-2022, hacktoberfest-accepted
